# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#menu-advanced-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "archives"
  pre = ""
  post = ""
  name = "文章"
  url = "/archives/"
  title = ""
  weight = 1
  [main.params]
    # icon = "fa-solid fa-archive"
    icon = "fa-solid fa-feather"
[[main]]
  identifier = "categories"
  parent = "archives"
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = ""
  weight = 2
  [main.params]
    icon = "fa-solid fa-folder-tree"
[[main]]
  identifier = "collections"
  parent = "archives"
  pre = ""
  post = ""
  name = "合集"
  url = "/collections/"
  title = ""
  weight = 3
  [main.params]
    icon = "fa-solid fa-layer-group"
[[main]]
  identifier = "tags"
  parent = "archives"
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = ""
  weight = 3
  [main.params]
    icon = "fa-solid fa-tags"
[[main]]
  identifier = "friends"
  pre = ""
  post = ""
  name = "友链"
  url = "/friends/"
  title = "友情链接"
  weight = 4
  [main.params]
    icon = "fa-solid fa-users-viewfinder"
[[main]]
  identifier = "guestbook"
  pre = ""
  post = ""
  name = "留言"
  url = "/guestbook/"
  title = ""
  weight = 6
  [main.params]
    icon = "fa-regular fa-comments"
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "关于"
  url = "/about/"
  title = ""
  weight = 100
  [main.params]
    icon = "fa-solid fa-quote-left"
[[main]]
  identifier = "github"
  pre = ""
  post = ""
  name = "关注 Follow"
  url = "https://github.com/Lruihao/hugo-blog"
  title = "GitHub"
  weight = ""
  [main.params]
    class = "text-center"
    icon = "fa-brands fa-github fa-lg"
    type = "mobile"
