name: Update theme components

# Controls when the workflow will run
on:
  schedule:
    # Update theme automatically every month
    - cron: '0 0 1 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: read
  id-token: write
jobs:
  update-theme-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ vars.HUGO_VERSION || 'latest' }}
          extended: true

      - name: Update theme components
        run: |
          hugo mod get -u
          hugo mod tidy
  
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: Chore(theme): update FixIt version'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
